### ISSUE TITLE
Feature request. Lock by button. 

### ISSUE THREAD

**Issue by nadidsky** [trustcrypto/libraries#11]
Would be great to be able to bind a button to a disconnect action. In this way i could lock the only key without disconnecting and connecting the key from the usb.

**Comment by onlykey** [comment]
@nadidsky Good idea. I think we could do that pretty easily. We would probably have it where you hold button 5 for 5 seconds to lock.

**Comment by nadidsky** [comment]
Sounds perfect :) or if it could be selectable would be also an option,
like all my buttons turns off my onlykey except long press on them, to
avoid accidental touches for instance. (It sends a special code that means
turn off)
