### ISSUE TITLE
Get ECC by label only compares final 8 characters of label

### ISSUE THREAD

**Issue by M-Pixel** [trustcrypto/libraries#13]
I noticed that for ECC keys, it doesn't offset the target buffer pointer by 8 [like the RSA implementation does](https://github.com/trustcrypto/libraries/issues/12) (`onlykey_flashget_label(ptr, (offset + i))` instead of `onlykey_flashget_label(ptr+8, (offset + i))`), but it _does_ still use only the final 8 characters in the comparison case (`keyid_match = memcmp (ptr+8, recv_buffer+6, 8);`). Is this a mistake?

**Comment by onlykey** [comment]
@M-Pixel Keylabels are not used by any apps currently. I think you are probably the only one that has used them. It a feature we are planning to use in the future but haven't yet where an app can request a keyid and if the device has that key it returns the slot where that key is. The keylabel would have to contain the keyid. We are redoing most of this code in the next release.
