### ISSUE TITLE
TOTP code returns "NOTSET" after configuration

### ISSUE THREAD

**Issue by jph** [trustcrypto/libraries#16]
I've configured TOTP in slot 1a. It initially works, but then if I unplug the OnlyKey, and plug it in again, unlock it with my PIN, when I attempt to use slot 1a, the TOTP code returned says "NOTSET".

Further to this, if I plug in the OnlyKey, unlock it with my PIN, then boot up the OnlyKey configuration application, the TOTP slot begins to work again. When I close the configuration program, the slot resumes outputting "NOTSET"

**Comment by onlykey** [comment]
@jph Thats because it requires the OnlyKey app to be running in order to get the current time. Or you can browse to https://apps.crp.to

**Comment by jph** [comment]
I understand. I thought that 'NOTSET' was a configuration issue, I didn't think that it was referring to the time. I appreciate the fast response, thank you! :+1:
